// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kijiuzvdjidbyiesnqrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpaml1enZkamlkYnlpZXNucXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTQyODQsImV4cCI6MjA3NDIzMDI4NH0.VoYNEzjwB6JUtI_YeJbtqArM13VfU0gJolEGg5MF1q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);